version: '3.8'

services:
  chatbot:
    build:
      context: .
      args:
        - PUBLIC_URL=http://localhost:3000
        - PORT=3000
    image: chatbot-alphaqueb
    ports:
      - "3300:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - MONGO_DB_URI=mongodb://mongoadmin:secret@mongo:27017/chatbotdb?authSource=admin
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4  # Usando la versión 4.4 que no requiere AVX
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - "27017:27017"

volumes:
  mongo_data:

